version: '3'

services:
  serviio:
    image: docker-serviio:latest
    network_mode: host
    dns:
    - 192.168.178.200
    ports:
     - "23423:23423/tcp"
     - "8895:8895/tcp"
     - "1900:1900/udp"
    volumes:
     - /home/me/movies:/media/serviio
